name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      - name: java
        uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 11
      - uses: nttld/setup-ndk@main
        with:
          ndk-version: r21e
      - name: script run line haha
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install hscript --quiet
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp --quiet
          haxelib git faxe https://github.com/ashea-code/faxe --quiet
          haxelib git polymod https://github.com/larsiusprime/polymod --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git extension-webm https://github.com/Sirox228/extension-webm --quiet
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --quiet
          haxelib run lime rebuild hxcpp
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib run lime build android
          haxelib install actuate 
          haxelib list
      - uses: actions/upload-artifact@main
        with:
          name: push
          path: export/release/android/bin/app/build/outputs/apk/debug
